services:
  - type: web
    name: url-auditor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_DEBUG
        value: "false"
      - key: PYTHON_VERSION
        value: "3.11.7"
